jobs:
  - script: >
      pipelineJob('example_run_job') {
        definition {
          cps {
            script('''@Library('testingLibrary') _
              TestBadEnv()'''.stripIndent())
            sandbox()
          }
        }
      }
